name: "common :: Build and analyse using Maven and Sonar"
description: "common :: Build and analyse using Maven and Sonar - requires checkout-java to be run before"

inputs:
  GITHUB_TOKEN:
    required: true
    description: "Just pass the secrets.GITHUB_TOKEN to this action as input."
  ROOT_POM_DIRECTORY:
    required: true
    description: "The directory where the root POM can be found."
  IGNORE_TEST_FAILURES:
    required: true
    description: "Whether to ignore test failures."
  SONAR_TOKEN:
    required: false
    description: "The token needed to push analyses to Sonar. Will skip this step if not provided."

runs:
  using: "composite"
  steps:
    - name: Build and analyze using Maven and Sonar
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
      shell: bash
      run: |
        SONAR_TOKEN=${{ inputs.SONAR_TOKEN }}
        mvn --no-transfer-progress -f ${{ inputs.ROOT_POM_DIRECTORY }}/pom.xml -Dmaven.test.failure.ignore=${{ inputs.IGNORE_TEST_FAILURES }} -P ${SONAR_TOKEN:+sonar,}publish verify ${SONAR_TOKEN:+org.sonarsource.scanner.maven:sonar-maven-plugin::sonar}

